image: python:3.7

stages:
  - test
  - quality
  - misc
  - deploy

before_script:
  - pip install tox

tests:
  stage: test
  script: tox -e py37
  artifacts:
    paths:
      - $CI_PROJECT_DIR/htmlcov
  coverage: '/^TOTAL(?:\s+\d+){4}\s+(\d+\%)$/'

lint:
  stage: quality
  script: tox -e lint

formatting:
  stage: quality
  script: tox -e formatting

py36:
  stage: misc
  image: python:3.6
  script: tox -e 36
  when: manual

pages:
  stage: deploy
  dependencies:
    - tests
  script:
    - mkdir -p doc/_static/coverage
    - cp -r $CI_PROJECT_DIR/htmlcov/* doc/_static/coverage/
    - tox -e doc
    - mv doc/_build public
  artifacts:
    paths:
      - public
  only:
    - master
