image: python:3.7

stages:
  - build
  - test

build:
  stage: build
  script:
    - make install

test:
  stage: test
  script:
    - make devdep coverage
  artifacts:
    paths:
      - $CI_PROJECT_DIR/htmlcov

quality:
  stage: test
  script:
      - make devdep quality
  allow_failure: true
