image: python:3.7

stages:
  - test
  - quality
  - misc
  - deploy

before_script:
  - pip install tox

tests:
  stage: test
  script: tox -e py37
  artifacts:
    paths:
      - $CI_PROJECT_DIR/htmlcov
    reports:
      junit: report*.xml
  coverage: '/^TOTAL(?:\s+\d+){4}\s+(\d+\%)$/'

lint:
  stage: quality
  script: tox -e lint

formatting:
  stage: quality
  script: tox -e formatting

py36:
  stage: misc
  image: python:3.6
  script: tox -e 36
  when: manual

docs:
  stage: misc
  dependencies:
    - tests
  script:
    - mkdir -p docs/_static/coverage
    - cp -r $CI_PROJECT_DIR/htmlcov/* docs/_static/coverage/
    - tox -e docs
  artifacts:
    paths:
      - html_docs

pages:
  stage: deploy
  dependencies:
    - docs
  script:
    - mv html_docs public
  artifacts:
    paths:
      - public
  only:
    - master
