image: python:3.7

stages:
  - test
  - quality
  - other_versions

before_script:
  - pip install tox

test:
  stage: test
  script: tox -e py37
  artifacts:
    paths:
      - $CI_PROJECT_DIR/htmlcov

lint:
  stage: quality
  script: tox -e lint

formatting:
  stage: quality
  script: tox -e formatting

py36:
  stage: other_versions
  image: python:3.6
  script: tox -e 36
  when: manual
